# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake

on:
  push:
    branches:
      - 'master'        # matches every branch

env:
  BUILD_TYPE: Release

jobs:
  latest-cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
          pwd
          ls ./
          # sudo apt-get -y update
          # sudo apt-get -y install libboost-dev
          # mkdir user-eph
          # mv * user-eph/
          # git clone -b stable https://github.com/lammps/lammps.git lammps
          # mv user-eph/* lammps/src
          # cd mylammps/src
          # make no-all
          # make yes-manybody
          # make yes-user-eph
          # make -j 8 mpi

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
          ls ./
